import socket
import struct


# Run protoc to generate python proto file
# (project root) protoc --python_out=path/to/output_directory input_file.proto
import ultracache_pb2  # generated by protoc

PROTO_VERSION = 1
MSG_TYPE_ENVELOPE = 1  # numeric enum value

def write_frame(sock: socket.socket, msg_type: int, payload: bytes):
    # frame_len = 1 byte version + 1 byte type + 2 byte flags + payload
    frame_len = 1 + 1 + 2 + len(payload)
    # >I = big-endian u32
    header = struct.pack(">I B B H",
                         frame_len,
                         PROTO_VERSION,
                         msg_type,
                         0)  # flags=0
    sock.sendall(header + payload)

def read_frame_header(sock: socket.socket):
    hdr = sock.recv(8)
    if len(hdr) < 8:
        raise ConnectionError("Incomplete header")
    frame_len, version, msg_type, flags = struct.unpack(">I B B H", hdr)
    return frame_len, version, msg_type, flags

def put_example():
    # 1) Connect
    sock = socket.create_connection(("127.0.0.1", 50051))
    
    # 2) Build the PutRequest envelope
    envelope = ultracache_pb2.Envelope(
        request_id=42,  # or any integer/UUID you choose
        put=ultracache_pb2.PutRequest(
            cache_name="default",
            key=b"my-key",
            value=b"hello world!"
        )
    )
    payload = envelope.SerializeToString()
    
    # 3) Send framed request
    write_frame(sock, MSG_TYPE_ENVELOPE, payload)
    
    # 4) Read response header + payload
    frame_len, version, msg_type, flags = read_frame_header(sock)
    body_len = frame_len - 4
    resp_payload = sock.recv(body_len)
    
    # 5) Decode EnvelopeResponse
    resp_env = ultracache_pb2.EnvelopeResponse()
    resp_env.ParseFromString(resp_payload)
    
    if resp_env.HasField("put_response"):
        ok = resp_env.put_response.success
        print("PUT successful?" , ok)
    elif resp_env.HasField("error"):
        print("Error from server:", resp_env.error.message)
    else:
        print("Unexpected response:", resp_env)
    
    sock.close()

if __name__ == "__main__":
    put_example()
