# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uc.msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cuc.msg.proto\x12\x06uc.msg\"\xba\x01\n\x08\x45nvelope\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12!\n\x03get\x18\n \x01(\x0b\x32\x12.uc.msg.GetRequestH\x00\x12!\n\x03put\x18\x0b \x01(\x0b\x32\x12.uc.msg.PutRequestH\x00\x12%\n\x05\x65vict\x18\x0c \x01(\x0b\x32\x14.uc.msg.EvictRequestH\x00\x12%\n\x05stats\x18\r \x01(\x0b\x32\x14.uc.msg.StatsRequestH\x00\x42\x06\n\x04\x62ody\"\x92\x02\n\x10\x45nvelopeResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12+\n\x0cget_response\x18\x14 \x01(\x0b\x32\x13.uc.msg.GetResponseH\x00\x12+\n\x0cput_response\x18\x15 \x01(\x0b\x32\x13.uc.msg.PutResponseH\x00\x12/\n\x0e\x65vict_response\x18\x16 \x01(\x0b\x32\x15.uc.msg.EvictResponseH\x00\x12/\n\x0estats_response\x18\x17 \x01(\x0b\x32\x15.uc.msg.StatsResponseH\x00\x12&\n\x05\x65rror\x18\x18 \x01(\x0b\x32\x15.uc.msg.ErrorResponseH\x00\x42\x06\n\x04\x62ody\"-\n\nGetRequest\x12\x12\n\ncache_name\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\"+\n\x0bGetResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x0c\"<\n\nPutRequest\x12\x12\n\ncache_name\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\r\n\x05value\x18\x03 \x01(\x0c\"\x1e\n\x0bPutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"/\n\x0c\x45victRequest\x12\x12\n\ncache_name\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\" \n\rEvictResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\x0cStatsRequest\x12\x12\n\ncache_name\x18\x01 \x01(\t\"B\n\rStatsResponse\x12\x0c\n\x04hits\x18\x01 \x01(\x04\x12\x0e\n\x06misses\x18\x02 \x01(\x04\x12\x13\n\x0b\x65ntry_count\x18\x03 \x01(\x04\".\n\rErrorResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uc.msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENVELOPE._serialized_start=25
  _ENVELOPE._serialized_end=211
  _ENVELOPERESPONSE._serialized_start=214
  _ENVELOPERESPONSE._serialized_end=488
  _GETREQUEST._serialized_start=490
  _GETREQUEST._serialized_end=535
  _GETRESPONSE._serialized_start=537
  _GETRESPONSE._serialized_end=580
  _PUTREQUEST._serialized_start=582
  _PUTREQUEST._serialized_end=642
  _PUTRESPONSE._serialized_start=644
  _PUTRESPONSE._serialized_end=674
  _EVICTREQUEST._serialized_start=676
  _EVICTREQUEST._serialized_end=723
  _EVICTRESPONSE._serialized_start=725
  _EVICTRESPONSE._serialized_end=757
  _STATSREQUEST._serialized_start=759
  _STATSREQUEST._serialized_end=793
  _STATSRESPONSE._serialized_start=795
  _STATSRESPONSE._serialized_end=861
  _ERRORRESPONSE._serialized_start=863
  _ERRORRESPONSE._serialized_end=909
# @@protoc_insertion_point(module_scope)
