// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod cache {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_WAL_PAYLOAD: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_WAL_PAYLOAD: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_WAL_PAYLOAD: [WalPayload; 3] = [
  WalPayload::NONE,
  WalPayload::WalPut,
  WalPayload::WalDelete,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct WalPayload(pub u8);
#[allow(non_upper_case_globals)]
impl WalPayload {
  pub const NONE: Self = Self(0);
  pub const WalPut: Self = Self(1);
  pub const WalDelete: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::WalPut,
    Self::WalDelete,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::WalPut => Some("WalPut"),
      Self::WalDelete => Some("WalDelete"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for WalPayload {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for WalPayload {
  type Inner = Self;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe {
      flatbuffers::read_scalar_at::<u8>(buf, loc)
    };
    Self(b)
  }
}

impl flatbuffers::Push for WalPayload {
    type Output = WalPayload;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        unsafe { flatbuffers::emplace_scalar::<u8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for WalPayload {
  #[inline]
  fn to_little_endian(self) -> Self {
    let b = u8::to_le(self.0);
    Self(b)
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(self) -> Self {
    let b = u8::from_le(self.0);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for WalPayload {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for WalPayload {}
pub struct WalPayloadUnionTableOffset {}

pub enum EntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Entry<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Entry<'a> {
  type Inner = Entry<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> Entry<'a> {
  pub const VT_VALUE: flatbuffers::VOffsetT = 4;
  pub const VT_EXPIRES_AT: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Entry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args EntryArgs<'args>
  ) -> flatbuffers::WIPOffset<Entry<'bldr>> {
    let mut builder = EntryBuilder::new(_fbb);
    builder.add_expires_at(args.expires_at);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> Option<&'a [u8]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Entry::VT_VALUE, None).map(|v| v.safe_slice())
  }
  #[inline]
  pub fn expires_at(&self) -> u64 {
    self._tab.get::<u64>(Entry::VT_EXPIRES_AT, Some(0)).unwrap()
  }
}

impl flatbuffers::Verifiable for Entry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("value", Self::VT_VALUE, false)?
     .visit_field::<u64>("expires_at", Self::VT_EXPIRES_AT, false)?
     .finish();
    Ok(())
  }
}
pub struct EntryArgs<'a> {
    pub value: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub expires_at: u64,
}
impl<'a> Default for EntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    EntryArgs {
      value: None,
      expires_at: 0,
    }
  }
}

pub struct EntryBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> EntryBuilder<'a, 'b> {
  #[inline]
  pub fn add_value(&mut self, value: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Entry::VT_VALUE, value);
  }
  #[inline]
  pub fn add_expires_at(&mut self, expires_at: u64) {
    self.fbb_.push_slot::<u64>(Entry::VT_EXPIRES_AT, expires_at, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> EntryBuilder<'a, 'b> {
    let start = _fbb.start_table();
    EntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Entry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Entry<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Entry");
      ds.field("value", &self.value());
      ds.field("expires_at", &self.expires_at());
      ds.finish()
  }
}
pub enum WalPutOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct WalPut<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for WalPut<'a> {
  type Inner = WalPut<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> WalPut<'a> {
  pub const VT_KEY: flatbuffers::VOffsetT = 4;
  pub const VT_ENTRY: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    WalPut { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args WalPutArgs<'args>
  ) -> flatbuffers::WIPOffset<WalPut<'bldr>> {
    let mut builder = WalPutBuilder::new(_fbb);
    if let Some(x) = args.entry { builder.add_entry(x); }
    if let Some(x) = args.key { builder.add_key(x); }
    builder.finish()
  }


  #[inline]
  pub fn key(&self) -> Option<&'a [u8]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(WalPut::VT_KEY, None).map(|v| v.safe_slice())
  }
  #[inline]
  pub fn entry(&self) -> Option<Entry<'a>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<Entry>>(WalPut::VT_ENTRY, None)
  }
}

impl flatbuffers::Verifiable for WalPut<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("key", Self::VT_KEY, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<Entry>>("entry", Self::VT_ENTRY, false)?
     .finish();
    Ok(())
  }
}
pub struct WalPutArgs<'a> {
    pub key: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub entry: Option<flatbuffers::WIPOffset<Entry<'a>>>,
}
impl<'a> Default for WalPutArgs<'a> {
  #[inline]
  fn default() -> Self {
    WalPutArgs {
      key: None,
      entry: None,
    }
  }
}

pub struct WalPutBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> WalPutBuilder<'a, 'b> {
  #[inline]
  pub fn add_key(&mut self, key: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(WalPut::VT_KEY, key);
  }
  #[inline]
  pub fn add_entry(&mut self, entry: flatbuffers::WIPOffset<Entry<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Entry>>(WalPut::VT_ENTRY, entry);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> WalPutBuilder<'a, 'b> {
    let start = _fbb.start_table();
    WalPutBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<WalPut<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for WalPut<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("WalPut");
      ds.field("key", &self.key());
      ds.field("entry", &self.entry());
      ds.finish()
  }
}
pub enum WalDeleteOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct WalDelete<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for WalDelete<'a> {
  type Inner = WalDelete<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> WalDelete<'a> {
  pub const VT_KEY: flatbuffers::VOffsetT = 4;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    WalDelete { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args WalDeleteArgs<'args>
  ) -> flatbuffers::WIPOffset<WalDelete<'bldr>> {
    let mut builder = WalDeleteBuilder::new(_fbb);
    if let Some(x) = args.key { builder.add_key(x); }
    builder.finish()
  }


  #[inline]
  pub fn key(&self) -> Option<&'a [u8]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(WalDelete::VT_KEY, None).map(|v| v.safe_slice())
  }
}

impl flatbuffers::Verifiable for WalDelete<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("key", Self::VT_KEY, false)?
     .finish();
    Ok(())
  }
}
pub struct WalDeleteArgs<'a> {
    pub key: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for WalDeleteArgs<'a> {
  #[inline]
  fn default() -> Self {
    WalDeleteArgs {
      key: None,
    }
  }
}

pub struct WalDeleteBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> WalDeleteBuilder<'a, 'b> {
  #[inline]
  pub fn add_key(&mut self, key: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(WalDelete::VT_KEY, key);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> WalDeleteBuilder<'a, 'b> {
    let start = _fbb.start_table();
    WalDeleteBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<WalDelete<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for WalDelete<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("WalDelete");
      ds.field("key", &self.key());
      ds.finish()
  }
}
pub enum WalRecordOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct WalRecord<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for WalRecord<'a> {
  type Inner = WalRecord<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> WalRecord<'a> {
  pub const VT_TIMESTAMP: flatbuffers::VOffsetT = 4;
  pub const VT_PAYLOAD_TYPE: flatbuffers::VOffsetT = 6;
  pub const VT_PAYLOAD: flatbuffers::VOffsetT = 8;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    WalRecord { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args WalRecordArgs
  ) -> flatbuffers::WIPOffset<WalRecord<'bldr>> {
    let mut builder = WalRecordBuilder::new(_fbb);
    builder.add_timestamp(args.timestamp);
    if let Some(x) = args.payload { builder.add_payload(x); }
    builder.add_payload_type(args.payload_type);
    builder.finish()
  }


  #[inline]
  pub fn timestamp(&self) -> u64 {
    self._tab.get::<u64>(WalRecord::VT_TIMESTAMP, Some(0)).unwrap()
  }
  #[inline]
  pub fn payload_type(&self) -> WalPayload {
    self._tab.get::<WalPayload>(WalRecord::VT_PAYLOAD_TYPE, Some(WalPayload::NONE)).unwrap()
  }
  #[inline]
  pub fn payload(&self) -> Option<flatbuffers::Table<'a>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(WalRecord::VT_PAYLOAD, None)
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_wal_put(&self) -> Option<WalPut<'a>> {
    if self.payload_type() == WalPayload::WalPut {
      self.payload().map(WalPut::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_wal_delete(&self) -> Option<WalDelete<'a>> {
    if self.payload_type() == WalPayload::WalDelete {
      self.payload().map(WalDelete::init_from_table)
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for WalRecord<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("timestamp", Self::VT_TIMESTAMP, false)?
     .visit_union::<WalPayload, _>("payload_type", Self::VT_PAYLOAD_TYPE, "payload", Self::VT_PAYLOAD, false, |key, v, pos| {
        match key {
          WalPayload::WalPut => v.verify_union_variant::<flatbuffers::ForwardsUOffset<WalPut>>("WalPayload::WalPut", pos),
          WalPayload::WalDelete => v.verify_union_variant::<flatbuffers::ForwardsUOffset<WalDelete>>("WalPayload::WalDelete", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct WalRecordArgs {
    pub timestamp: u64,
    pub payload_type: WalPayload,
    pub payload: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for WalRecordArgs {
  #[inline]
  fn default() -> Self {
    WalRecordArgs {
      timestamp: 0,
      payload_type: WalPayload::NONE,
      payload: None,
    }
  }
}

pub struct WalRecordBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> WalRecordBuilder<'a, 'b> {
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: u64) {
    self.fbb_.push_slot::<u64>(WalRecord::VT_TIMESTAMP, timestamp, 0);
  }
  #[inline]
  pub fn add_payload_type(&mut self, payload_type: WalPayload) {
    self.fbb_.push_slot::<WalPayload>(WalRecord::VT_PAYLOAD_TYPE, payload_type, WalPayload::NONE);
  }
  #[inline]
  pub fn add_payload(&mut self, payload: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(WalRecord::VT_PAYLOAD, payload);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> WalRecordBuilder<'a, 'b> {
    let start = _fbb.start_table();
    WalRecordBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<WalRecord<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for WalRecord<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("WalRecord");
      ds.field("timestamp", &self.timestamp());
      ds.field("payload_type", &self.payload_type());
      match self.payload_type() {
        WalPayload::WalPut => {
          if let Some(x) = self.payload_as_wal_put() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        WalPayload::WalDelete => {
          if let Some(x) = self.payload_as_wal_delete() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("payload", &x)
        },
      };
      ds.finish()
  }
}
#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_root_as_wal_record<'a>(buf: &'a [u8]) -> WalRecord<'a> {
  unsafe { flatbuffers::root_unchecked::<WalRecord<'a>>(buf) }
}

#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_size_prefixed_root_as_wal_record<'a>(buf: &'a [u8]) -> WalRecord<'a> {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<WalRecord<'a>>(buf) }
}

#[inline]
/// Verifies that a buffer of bytes contains a `WalRecord`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_wal_record_unchecked`.
pub fn root_as_wal_record(buf: &[u8]) -> Result<WalRecord, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<WalRecord>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `WalRecord` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_wal_record_unchecked`.
pub fn size_prefixed_root_as_wal_record(buf: &[u8]) -> Result<WalRecord, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<WalRecord>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `WalRecord` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_wal_record_unchecked`.
pub fn root_as_wal_record_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<WalRecord<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<WalRecord<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `WalRecord` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_wal_record_unchecked`.
pub fn size_prefixed_root_as_wal_record_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<WalRecord<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<WalRecord<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a WalRecord and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `WalRecord`.
pub unsafe fn root_as_wal_record_unchecked(buf: &[u8]) -> WalRecord {
  flatbuffers::root_unchecked::<WalRecord>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed WalRecord and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `WalRecord`.
pub unsafe fn size_prefixed_root_as_wal_record_unchecked(buf: &[u8]) -> WalRecord {
  flatbuffers::size_prefixed_root_unchecked::<WalRecord>(buf)
}
#[inline]
pub fn finish_wal_record_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<WalRecord<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_wal_record_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<WalRecord<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod cache

