// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod cache {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_COMMAND: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_COMMAND: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_COMMAND: [Command; 4] = [
  Command::NONE,
  Command::SetCommand,
  Command::DeleteCommand,
  Command::SnapshotCommand,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Command(pub u8);
#[allow(non_upper_case_globals)]
impl Command {
  pub const NONE: Self = Self(0);
  pub const SetCommand: Self = Self(1);
  pub const DeleteCommand: Self = Self(2);
  pub const SnapshotCommand: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::SetCommand,
    Self::DeleteCommand,
    Self::SnapshotCommand,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::SetCommand => Some("SetCommand"),
      Self::DeleteCommand => Some("DeleteCommand"),
      Self::SnapshotCommand => Some("SnapshotCommand"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for Command {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for Command {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for Command {
    type Output = Command;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for Command {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for Command {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Command {}
pub struct CommandUnionTableOffset {}

pub enum SetCommandOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SetCommand<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SetCommand<'a> {
  type Inner = SetCommand<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> SetCommand<'a> {
  pub const VT_KEY: flatbuffers::VOffsetT = 4;
  pub const VT_VALUE: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SetCommand { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SetCommandArgs<'args>
  ) -> flatbuffers::WIPOffset<SetCommand<'bldr>> {
    let mut builder = SetCommandBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    if let Some(x) = args.key { builder.add_key(x); }
    builder.finish()
  }


  #[inline]
  pub fn key(&self) -> flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(SetCommand::VT_KEY, None).unwrap()}
  }
  #[inline]
  pub fn value(&self) -> flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(SetCommand::VT_VALUE, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for SetCommand<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("key", Self::VT_KEY, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("value", Self::VT_VALUE, true)?
     .finish();
    Ok(())
  }
}
pub struct SetCommandArgs<'a> {
    pub key: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub value: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for SetCommandArgs<'a> {
  #[inline]
  fn default() -> Self {
    SetCommandArgs {
      key: None, // required field
      value: None, // required field
    }
  }
}

pub struct SetCommandBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SetCommandBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_key(&mut self, key: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SetCommand::VT_KEY, key);
  }
  #[inline]
  pub fn add_value(&mut self, value: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SetCommand::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SetCommandBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SetCommandBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SetCommand<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, SetCommand::VT_KEY,"key");
    self.fbb_.required(o, SetCommand::VT_VALUE,"value");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SetCommand<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SetCommand");
      ds.field("key", &self.key());
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum DeleteCommandOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DeleteCommand<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DeleteCommand<'a> {
  type Inner = DeleteCommand<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> DeleteCommand<'a> {
  pub const VT_KEY: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DeleteCommand { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DeleteCommandArgs<'args>
  ) -> flatbuffers::WIPOffset<DeleteCommand<'bldr>> {
    let mut builder = DeleteCommandBuilder::new(_fbb);
    if let Some(x) = args.key { builder.add_key(x); }
    builder.finish()
  }


  #[inline]
  pub fn key(&self) -> flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(DeleteCommand::VT_KEY, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for DeleteCommand<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("key", Self::VT_KEY, true)?
     .finish();
    Ok(())
  }
}
pub struct DeleteCommandArgs<'a> {
    pub key: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for DeleteCommandArgs<'a> {
  #[inline]
  fn default() -> Self {
    DeleteCommandArgs {
      key: None, // required field
    }
  }
}

pub struct DeleteCommandBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> DeleteCommandBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_key(&mut self, key: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DeleteCommand::VT_KEY, key);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> DeleteCommandBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DeleteCommandBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DeleteCommand<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, DeleteCommand::VT_KEY,"key");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DeleteCommand<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DeleteCommand");
      ds.field("key", &self.key());
      ds.finish()
  }
}
pub enum SnapshotCommandOffset {}
#[derive(Copy, Clone, PartialEq)]

/// SnapshotCommand captures a point-in-time snapshot of the state machine.
pub struct SnapshotCommand<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SnapshotCommand<'a> {
  type Inner = SnapshotCommand<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> SnapshotCommand<'a> {
  pub const VT_SNAPSHOT_TERM: flatbuffers::VOffsetT = 4;
  pub const VT_SNAPSHOT_INDEX: flatbuffers::VOffsetT = 6;
  pub const VT_CHECKSUM: flatbuffers::VOffsetT = 8;
  pub const VT_DATA: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SnapshotCommand { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SnapshotCommandArgs<'args>
  ) -> flatbuffers::WIPOffset<SnapshotCommand<'bldr>> {
    let mut builder = SnapshotCommandBuilder::new(_fbb);
    builder.add_checksum(args.checksum);
    builder.add_snapshot_index(args.snapshot_index);
    builder.add_snapshot_term(args.snapshot_term);
    if let Some(x) = args.data { builder.add_data(x); }
    builder.finish()
  }


  #[inline]
  pub fn snapshot_term(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(SnapshotCommand::VT_SNAPSHOT_TERM, Some(0)).unwrap()}
  }
  #[inline]
  pub fn snapshot_index(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(SnapshotCommand::VT_SNAPSHOT_INDEX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn checksum(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(SnapshotCommand::VT_CHECKSUM, Some(0)).unwrap()}
  }
  #[inline]
  pub fn data(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(SnapshotCommand::VT_DATA, None)}
  }
}

impl flatbuffers::Verifiable for SnapshotCommand<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("snapshot_term", Self::VT_SNAPSHOT_TERM, false)?
     .visit_field::<u64>("snapshot_index", Self::VT_SNAPSHOT_INDEX, false)?
     .visit_field::<u64>("checksum", Self::VT_CHECKSUM, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("data", Self::VT_DATA, false)?
     .finish();
    Ok(())
  }
}
pub struct SnapshotCommandArgs<'a> {
    pub snapshot_term: u64,
    pub snapshot_index: u64,
    pub checksum: u64,
    pub data: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for SnapshotCommandArgs<'a> {
  #[inline]
  fn default() -> Self {
    SnapshotCommandArgs {
      snapshot_term: 0,
      snapshot_index: 0,
      checksum: 0,
      data: None,
    }
  }
}

pub struct SnapshotCommandBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SnapshotCommandBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_snapshot_term(&mut self, snapshot_term: u64) {
    self.fbb_.push_slot::<u64>(SnapshotCommand::VT_SNAPSHOT_TERM, snapshot_term, 0);
  }
  #[inline]
  pub fn add_snapshot_index(&mut self, snapshot_index: u64) {
    self.fbb_.push_slot::<u64>(SnapshotCommand::VT_SNAPSHOT_INDEX, snapshot_index, 0);
  }
  #[inline]
  pub fn add_checksum(&mut self, checksum: u64) {
    self.fbb_.push_slot::<u64>(SnapshotCommand::VT_CHECKSUM, checksum, 0);
  }
  #[inline]
  pub fn add_data(&mut self, data: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SnapshotCommand::VT_DATA, data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SnapshotCommandBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SnapshotCommandBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SnapshotCommand<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SnapshotCommand<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SnapshotCommand");
      ds.field("snapshot_term", &self.snapshot_term());
      ds.field("snapshot_index", &self.snapshot_index());
      ds.field("checksum", &self.checksum());
      ds.field("data", &self.data());
      ds.finish()
  }
}
pub enum WalRecordOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct WalRecord<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for WalRecord<'a> {
  type Inner = WalRecord<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> WalRecord<'a> {
  pub const VT_TERM: flatbuffers::VOffsetT = 4;
  pub const VT_INDEX: flatbuffers::VOffsetT = 6;
  pub const VT_OP_TYPE: flatbuffers::VOffsetT = 8;
  pub const VT_OP: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    WalRecord { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args WalRecordArgs
  ) -> flatbuffers::WIPOffset<WalRecord<'bldr>> {
    let mut builder = WalRecordBuilder::new(_fbb);
    builder.add_index(args.index);
    builder.add_term(args.term);
    if let Some(x) = args.op { builder.add_op(x); }
    builder.add_op_type(args.op_type);
    builder.finish()
  }


  #[inline]
  pub fn term(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(WalRecord::VT_TERM, Some(0)).unwrap()}
  }
  #[inline]
  pub fn index(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(WalRecord::VT_INDEX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn op_type(&self) -> Command {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Command>(WalRecord::VT_OP_TYPE, Some(Command::NONE)).unwrap()}
  }
  #[inline]
  pub fn op(&self) -> Option<flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(WalRecord::VT_OP, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn op_as_set_command(&self) -> Option<SetCommand<'a>> {
    if self.op_type() == Command::SetCommand {
      self.op().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { SetCommand::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn op_as_delete_command(&self) -> Option<DeleteCommand<'a>> {
    if self.op_type() == Command::DeleteCommand {
      self.op().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { DeleteCommand::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn op_as_snapshot_command(&self) -> Option<SnapshotCommand<'a>> {
    if self.op_type() == Command::SnapshotCommand {
      self.op().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { SnapshotCommand::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for WalRecord<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("term", Self::VT_TERM, false)?
     .visit_field::<u64>("index", Self::VT_INDEX, false)?
     .visit_union::<Command, _>("op_type", Self::VT_OP_TYPE, "op", Self::VT_OP, false, |key, v, pos| {
        match key {
          Command::SetCommand => v.verify_union_variant::<flatbuffers::ForwardsUOffset<SetCommand>>("Command::SetCommand", pos),
          Command::DeleteCommand => v.verify_union_variant::<flatbuffers::ForwardsUOffset<DeleteCommand>>("Command::DeleteCommand", pos),
          Command::SnapshotCommand => v.verify_union_variant::<flatbuffers::ForwardsUOffset<SnapshotCommand>>("Command::SnapshotCommand", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct WalRecordArgs {
    pub term: u64,
    pub index: u64,
    pub op_type: Command,
    pub op: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for WalRecordArgs {
  #[inline]
  fn default() -> Self {
    WalRecordArgs {
      term: 0,
      index: 0,
      op_type: Command::NONE,
      op: None,
    }
  }
}

pub struct WalRecordBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> WalRecordBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_term(&mut self, term: u64) {
    self.fbb_.push_slot::<u64>(WalRecord::VT_TERM, term, 0);
  }
  #[inline]
  pub fn add_index(&mut self, index: u64) {
    self.fbb_.push_slot::<u64>(WalRecord::VT_INDEX, index, 0);
  }
  #[inline]
  pub fn add_op_type(&mut self, op_type: Command) {
    self.fbb_.push_slot::<Command>(WalRecord::VT_OP_TYPE, op_type, Command::NONE);
  }
  #[inline]
  pub fn add_op(&mut self, op: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(WalRecord::VT_OP, op);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> WalRecordBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    WalRecordBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<WalRecord<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for WalRecord<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("WalRecord");
      ds.field("term", &self.term());
      ds.field("index", &self.index());
      ds.field("op_type", &self.op_type());
      match self.op_type() {
        Command::SetCommand => {
          if let Some(x) = self.op_as_set_command() {
            ds.field("op", &x)
          } else {
            ds.field("op", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Command::DeleteCommand => {
          if let Some(x) = self.op_as_delete_command() {
            ds.field("op", &x)
          } else {
            ds.field("op", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Command::SnapshotCommand => {
          if let Some(x) = self.op_as_snapshot_command() {
            ds.field("op", &x)
          } else {
            ds.field("op", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("op", &x)
        },
      };
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `WalRecord`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_wal_record_unchecked`.
pub fn root_as_wal_record(buf: &[u8]) -> Result<WalRecord, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<WalRecord>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `WalRecord` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_wal_record_unchecked`.
pub fn size_prefixed_root_as_wal_record(buf: &[u8]) -> Result<WalRecord, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<WalRecord>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `WalRecord` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_wal_record_unchecked`.
pub fn root_as_wal_record_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<WalRecord<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<WalRecord<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `WalRecord` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_wal_record_unchecked`.
pub fn size_prefixed_root_as_wal_record_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<WalRecord<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<WalRecord<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a WalRecord and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `WalRecord`.
pub unsafe fn root_as_wal_record_unchecked(buf: &[u8]) -> WalRecord {
  flatbuffers::root_unchecked::<WalRecord>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed WalRecord and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `WalRecord`.
pub unsafe fn size_prefixed_root_as_wal_record_unchecked(buf: &[u8]) -> WalRecord {
  flatbuffers::size_prefixed_root_unchecked::<WalRecord>(buf)
}
pub const WAL_RECORD_IDENTIFIER: &str = "WALR";

#[inline]
pub fn wal_record_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, WAL_RECORD_IDENTIFIER, false)
}

#[inline]
pub fn wal_record_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, WAL_RECORD_IDENTIFIER, true)
}

#[inline]
pub fn finish_wal_record_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<WalRecord<'a>>) {
  fbb.finish(root, Some(WAL_RECORD_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_wal_record_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<WalRecord<'a>>) {
  fbb.finish_size_prefixed(root, Some(WAL_RECORD_IDENTIFIER));
}
}  // pub mod cache

